In [2]:
import numpy as np
import pandas as pd

In [19]:
file_path = "/Users/liuzhongfei/Documents/happy_machine_learning/ linear_regression/data/USA_Housing.csv"

In [20]:
file = pd.read_csv(file_path, )
file.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price
0,79545.458574,5.682861,7.009188,4.09,23086.800503,1.059034e+06
1,79248.642455,6.002900,6.730821,3.09,40173.072174,1.505891e+06
2,61287.067179,5.865890,8.512727,5.13,36882.159400,1.058988e+06
3,63345.240046,7.188236,5.586729,3.26,34310.242831,1.260617e+06
4,59982.197226,5.040555,7.839388,4.23,26354.109472,6.309435e+05

In [21]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Avg. Area Income              5000 non-null   float64
 1   Avg. Area House Age           5000 non-null   float64
 2   Avg. Area Number of Rooms     5000 non-null   float64
 3   Avg. Area Number of Bedrooms  5000 non-null   float64
 4   Area Population               5000 non-null   float64
 5   Price                         5000 non-null   float64
dtypes: float64(6)
memory usage: 234.5 KB

In [22]:
file.describe()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5.000000e+03
mean,68583.108984,5.977222,6.987792,3.981330,36163.516039,1.232073e+06
std,10657.991214,0.991456,1.005833,1.234137,9925.650114,3.531176e+05
min,17796.631190,2.644304,3.236194,2.000000,172.610686,1.593866e+04
25%,61480.562388,5.322283,6.299250,3.140000,29403.928702,9.975771e+05
50%,68804.286404,5.970429,7.002902,4.050000,36199.406689,1.232669e+06
75%,75783.338666,6.650808,7.665871,4.490000,42861.290769,1.471210e+06
max,107701.748378,9.519088,10.759588,6.500000,69621.713378,2.469066e+06

In [26]:
# 划分数据集与训练集
file = file.sample(frac = 1, random_state = 42).reset_index(drop = True) # 打乱数据集
ration = 0.8
split = int(len(file) * ration)
train, test = file[:split], file[split:]
print(train.shape, test.shape)

(4000, 6) (1000, 6)

In [ ]:
# 数据标准化

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price
0,61907.593345,7.017838,6.440256,3.25,43828.947207,1.339096e+06
1,57160.202243,6.893260,6.921532,3.13,43467.147035,1.251794e+06
2,70190.796445,6.745054,6.662567,2.01,29215.136112,1.340095e+06
3,69316.796889,6.300409,7.873576,4.28,24448.211461,1.431508e+06
4,72991.481649,3.412866,6.494081,2.48,50626.495426,1.042374e+06
...,...,...,...,...,...,...
3995,86249.993070,6.155403,7.967184,4.39,43154.838627,1.749820e+06
3996,69528.557433,6.058146,5.664156,3.00,33176.038447,9.951372e+05
3997,64400.265086,5.270539,8.404179,3.40,26605.375797,1.110932e+06
3998,77514.593544,4.138823,6.812797,2.33,30820.807768,9.850593e+05
3999,62820.179077,7.639741,7.681444,6.07,23734.169591,1.285158e+06